### ISSUE TITLE
datahub的datahub-web-react-i18模块编译问题

### ISSUE THREAD

**Issue by javaht** [alldatacenter/alldata#565]
环境：
node  v14.15.4
npm  6.14.10
yarn  1.22.19

猜测：少什么依赖
报错如下：
PS C:\ideaworkplace\datahub\datahub-web-react-i18> yarn run start
yarn run v1.22.19
$ yarn run generate && cross-env BROWSER=none REACT_APP_MOCK=false craco start
$ cross-env graphql-codegen --config codegen.yml
  √ Parse configuration
  > Generate outputs
    > Generate src/types.generated.ts
      √ Load GraphQL schemas
      √ Load GraphQL documents
      × Generate
        →         at C:/ideaworkplace/datahub/datahub-web-react-i18/src/graphql/quickFilters.graphql:2:5
    > Generate to src/ (using EXPERIMENTAL preset "near-operation-file")
      √ Load GraphQL schemas
      √ Load GraphQL documents
      × Generate
        → Unable to validate GraphQL document!

 Found 2 errors

  × src/types.generated.ts
    AggregateError: 
        GraphQLDocumentError: Unknown type "GetQuickFiltersInput". Did you mean "ResourceFilterInput", "ActorFilterInput", "AndFilterInput", "DataHubViewFilterInput", or "FacetFilterInput"?
            at C:/ideaworkplace/datahub/datahub-web-react-i18/src/graphql/quickFilters.graphql:1:31
        GraphQLDocumentError: Cannot query field "getQuickFilters" on type "Query".
            at C:/ideaworkplace/datahub/datahub-web-react-i18/src/graphql/quickFilters.graphql:2:5
        at new AggregateError (C:\ideaworkplace\datahub\datahub-web-react-i18\node_modules\@ardatan\aggregate-error\index.cjs.js:141:24)
        at Object.checkValidationErrors (C:\ideaworkplace\datahub\datahub-web-react-i18\node_modules\@graphql-codegen\core\node_modules\@graphql-tools\utils\index.cjs.js:517:15)
        at Object.codegen (C:\ideaworkplace\datahub\datahub-web-react-i18\node_modules\@graphql-codegen\core\index.cjs.js:102:15)
        at async process (C:\ideaworkplace\datahub\datahub-web-react-i18\node_modules\@graphql-codegen\cli\bin.js:940:56)
        at async Promise.all (index 0)
        at async C:\ideaworkplace\datahub\datahub-web-react-i18\node_modules\@graphql-codegen\cli\bin.js:947:37
        at async Task.task (C:\ideaworkplace\datahub\datahub-web-react-i18\node_modules\@graphql-codegen\cli\bin.js:725:17)
    AggregateError: 
        GraphQLDocumentError: Unknown type "GetQuickFiltersInput". Did you mean "ResourceFilterInput", "ActorFilterInput", "AndFilterInput", "DataHubViewFilterInput", or "FacetFilterInput"?
            at C:/ideaworkplace/datahub/datahub-web-react-i18/src/graphql/quickFilters.graphql:1:31
        GraphQLDocumentError: Cannot query field "getQuickFilters" on type "Query".
            at C:/ideaworkplace/datahub/datahub-web-react-i18/src/graphql/quickFilters.graphql:2:5
        at new AggregateError (C:\ideaworkplace\datahub\datahub-web-react-i18\node_modules\@ardatan\aggregate-error\index.cjs.js:141:24)
        at Object.checkValidationErrors (C:\ideaworkplace\datahub\datahub-web-react-i18\node_modules\@graphql-codegen\core\node_modules\@graphql-tools\utils\index.cjs.js:517:15)
        at Object.codegen (C:\ideaworkplace\datahub\datahub-web-react-i18\node_modules\@graphql-codegen\core\index.cjs.js:102:15)
        at C:\ideaworkplace\datahub\datahub-web-react-i18\node_modules\@graphql-codegen\near-operation-file-preset\index.cjs.js:206:19
        at Array.map (<anonymous>)
        at resolveDocumentImports (C:\ideaworkplace\datahub\datahub-web-react-i18\node_modules\@graphql-codegen\near-operation-file-preset\index.cjs.js:182:22)
        at Object.buildGeneratesSection (C:\ideaworkplace\datahub\datahub-web-react-i18\node_modules\@graphql-codegen\near-operation-file-preset\index.cjs.js:234:25)
        at C:\ideaworkplace\datahub\datahub-web-react-i18\node_modules\@graphql-codegen\cli\bin.js:913:64
        at async Task.task (C:\ideaworkplace\datahub\datahub-web-react-i18\node_modules\@graphql-codegen\cli\bin.js:725:17)

Something went wrong
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
PS C:\ideaworkplace\datahub\datahub-web-react-i18>

        at C:\ideaworkplace\datahub\datahub-web-react-i18\node_modules\@graphql-codegen\near-operation-file-preset\index.cjs.js:206:19
        at Array.map (<anonymous>)
        at resolveDocumentImports (C:\ideaworkplace\datahub\datahub-web-react-i18\node_modules\@graphql-codegen\near-operation-file-preset\index.cjs.js:182:22)
        at Object.buildGeneratesSection (C:\ideaworkplace\datahub\datahub-web-react-i18\node_modules\@graphql-codegen\near-operation-file-preset\index.cjs.js:234:25)
        at C:\ideaworkplace\datahub\datahub-web-react-i18\node_modules\@graphql-codegen\cli\bin.js:913:64
        at async Task.task (C:\ideaworkplace\datahub\datahub-web-react-i18\node_modules\@graphql-codegen\cli\bin.js:725:17)

Something went wrong
error Command failed with exit code 1.                                                                                                                                                                                                  
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
PS C:\ideaworkplace\datahub\datahub-web-react-i18>

        at C:\ideaworkplace\datahub\datahub-web-react-i18\node_modules\@graphql-codegen\cli\bin.js:913:64
        at C:\ideaworkplace\datahub\datahub-web-react-i18\node_modules\@graphql-codegen\cli\bin.js:913:64
        at async Task.task (C:\ideaworkplace\datahub\datahub-web-react-i18\node_modules\@graphql-codegen\cli\bin.js:725:17)
        at async Task.task (C:\ideaworkplace\datahub\datahub-web-react-i18\node_modules\@graphql-codegen\cli\bin.js:725:17)
 

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by javaht** [comment]
没有启动datahub

**Comment by sfdgdfh** [comment]
> 没有启动datahub

why the project without i18  can build or start
