### ISSUE TITLE
关于部署的一些问题

### ISSUE THREAD

**Issue by HZNU-Qiu** [alldatacenter/alldata#620]
您好，最近在部署alldata-studio项目，在部署的过程中遇到了一些问题，想向您请教一下：
1. quartz-service服务启动报错，报错内容如下：
```2023-08-10 16:57:10 ERROR service-quartz main org.springframework.boot.SpringApplication Application run failed
java.lang.IllegalStateException: Failed to execute ApplicationRunner
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:778)
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:765)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:322)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
        at cn.datax.service.quartz.DataxQuartzApplication.main(DataxQuartzApplication.java:14)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
Caused by: cn.datax.common.exception.DataException: 创建定时任务失败
        at cn.datax.service.quartz.quartz.utils.ScheduleUtil.createScheduleJob(ScheduleUtil.java:104)
        at cn.datax.service.quartz.quartz.utils.ScheduleUtil.init(ScheduleUtil.java:202)
        at cn.datax.service.quartz.config.StartedUpRunner.run(StartedUpRunner.java:40)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:775)
        ... 13 common frames omitted
Caused by: org.quartz.impl.jdbcjobstore.LockException: Failure obtaining db row lock: Table 'studio.QRTZ_LOCKS' doesn't exist
        at org.quartz.impl.jdbcjobstore.StdRowLockSemaphore.executeSQL(StdRowLockSemaphore.java:184)
        at org.quartz.impl.jdbcjobstore.DBSemaphore.obtainLock(DBSemaphore.java:113)
        at org.quartz.impl.jdbcjobstore.JobStoreCMT.executeInLock(JobStoreCMT.java:238)
        at org.quartz.impl.jdbcjobstore.JobStoreSupport.storeJobAndTrigger(JobStoreSupport.java:1063)
        at org.quartz.core.QuartzScheduler.scheduleJob(QuartzScheduler.java:855)
        at org.quartz.impl.StdScheduler.scheduleJob(StdScheduler.java:249)
        at cn.datax.service.quartz.quartz.utils.ScheduleUtil.createScheduleJob(ScheduleUtil.java:98)
        ... 16 common frames omitted
Caused by: java.sql.SQLSyntaxErrorException: Table 'studio.QRTZ_LOCKS' doesn't exist
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:955)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1005)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
        at org.quartz.impl.jdbcjobstore.StdRowLockSemaphore.executeSQL(StdRowLockSemaphore.java:123)
        ... 22 common frames omitted
```
这事怎么一回事？

2. 第二个问题：前端部署后，配置了nginx，但是出现
```
Access to XMLHttpRequest at 'http://192.168.45.100:9538/system/auth/code' from origin 'http://192.168.45.100' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header contains multiple values 'http://192.168.45.100, http://192.168.45.100', but only one is allowed.
```
问题。
我的nginx配置如下：
```
user  www www;
worker_processes auto;
error_log  /www/wwwlogs/nginx_error.log  crit;
pid        /www/server/nginx/logs/nginx.pid;
worker_rlimit_nofile 51200;

stream {
    log_format tcp_format '$time_local|$remote_addr|$protocol|$status|$bytes_sent|$bytes_received|$session_time|$upstream_addr|$upstream_bytes_sent|$upstream_bytes_received|$upstream_connect_time';
  
    access_log /www/wwwlogs/tcp-access.log tcp_format;
    error_log /www/wwwlogs/tcp-error.log;
    include /www/server/panel/vhost/nginx/tcp/*.conf;
}

events
    {
        use epoll;
        worker_connections 51200;
        multi_accept on;
    }

http
    {
        include       mime.types;
		#include luawaf.conf;

		include proxy.conf;
        lua_package_path "/www/server/nginx/lib/lua/?.lua;;";

        default_type  application/octet-stream;

        server_names_hash_bucket_size 512;
        client_header_buffer_size 32k;
        large_client_header_buffers 4 32k;
        client_max_body_size 50m;

        sendfile   on;
        tcp_nopush on;

        keepalive_timeout 60;

        tcp_nodelay on;

        fastcgi_connect_timeout 300;
        fastcgi_send_timeout 300;
        fastcgi_read_timeout 300;
        fastcgi_buffer_size 64k;
        fastcgi_buffers 4 64k;
        fastcgi_busy_buffers_size 128k;
        fastcgi_temp_file_write_size 256k;
		fastcgi_intercept_errors on;

        gzip on;
        gzip_min_length  1k;
        gzip_buffers     4 16k;
        gzip_http_version 1.1;
        gzip_comp_level 2;
        gzip_types     text/plain application/javascript application/x-javascript text/javascript text/css application/xml;
        gzip_vary on;
        gzip_proxied   expired no-cache no-store private auth;
        gzip_disable   "MSIE [1-6]\.";

        limit_conn_zone $binary_remote_addr zone=perip:10m;
		limit_conn_zone $server_name zone=perserver:10m;

        server_tokens off;
        access_log off;

server
    {
        listen 80;
        server_name 192.168.45.100/;
        # 添加下面的头部配置
        #add_header Access-Control-Allow-Origin *;
        #add_header Access-Control-Allow-Credentials true;
        #add_header Access-Control-Allow-Methods "GET, POST, OPTIONS";
        #add_header Access-Control-Allow-Headers "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range";
        index index.html index.htm index.php;
        
        location / {
			    root  /www/studio-release-0.4.x/16gmaster/ui/dist;
			    index index.html;
			    try_files $uri $uri/ /index.html;
		    }
        location /api/ {
			    proxy_pass  http://192.168.45.100:9538/;
			    proxy_set_header Host $proxy_host;
			    proxy_set_header X-Real-IP $remote_addr;
			    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;	  
		    }
    }
}
```
关于
```
add_header Access-Control-Allow-Origin *;
        #add_header Access-Control-Allow-Credentials true;
        #add_header Access-Control-Allow-Methods "GET, POST, OPTIONS";
```
这个部分我也尝试了注释和不注释其最终结果都是报那个错误。

3.第三个问题：我本地npm run dev跑的前端项目（没办法了）但是，新增，查询业务都可以进行，但是修改，删除业务全部失败，失败的报错是：
```
PUT http://192.168.45.100:8013/system/api/job net::ERR_CONNECTION_RESET
```
以上3个问题想向您请教，还请您在百忙之余中帮我看看，谢谢~

**Comment by ProductManage-Leo** [comment]
1、数据库开启大小不敏感
2、nginx的header都关闭试试
3、问题3是修改删除什么业务？
