### ISSUE TITLE
Error: Invalid version: "0.4.x"

### ISSUE THREAD

**Issue by yangtzelsl** [alldatacenter/alldata#646]
拉取最新的master代码后，构建报错，报错信息为
> micro-ui@0.4.x dev
> vue-cli-service serve --port 8013

E:\IDEA2018\valuable-project\alldata20230830\alldata\studio\micro-ui\node_modules\normalize-package-data\lib\fixer.js:191
      throw new Error('Invalid version: "'+ data.version + '"')
      ^

Error: Invalid version: "0.4.x"
    at Object.fixVersionField (E:\IDEA2018\valuable-project\alldata20230830\alldata\studio\micro-ui\node_modules\normalize-package-data\lib\fixer.js:191:13)
    at E:\IDEA2018\valuable-project\alldata20230830\alldata\studio\micro-ui\node_modules\normalize-package-data\lib\normalize.js:32:38
    at Array.forEach (<anonymous>)
    at normalize (E:\IDEA2018\valuable-project\alldata20230830\alldata\studio\micro-ui\node_modules\normalize-package-data\lib\normalize.js:31:15)
    at Function.module.exports.sync (E:\IDEA2018\valuable-project\alldata20230830\alldata\studio\micro-ui\node_modules\read-pkg\index.js:38:36)
    at Service.resolvePkg (E:\IDEA2018\valuable-project\alldata20230830\alldata\studio\micro-ui\node_modules\@vue\cli-service\lib\Service.js:47:27)
    at new Service (E:\IDEA2018\valuable-project\alldata20230830\alldata\studio\micro-ui\node_modules\@vue\cli-service\lib\Service.js:29:21)
    at Object.<anonymous> (E:\IDEA2018\valuable-project\alldata20230830\alldata\studio\micro-ui\node_modules\@vue\cli-service\bin\vue-cli-service.js:16:17) 
    at Module._compile (node:internal/modules/cjs/loader:1196:14)

我的node版本和npm版本分别是
C:\Users\20190627>node -v
v16.20.0

C:\Users\20190627>npm -v
8.19.4

想升级npm的版本为10.15.3，也是一直报错
C:\Users\20190627>npm install -g npm@10.15.3
npm ERR! code ETARGET
npm ERR! notarget No matching version found for npm@10.15.3.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\20190627\AppData\Local\npm-cache\_logs\2023-09-08T15_24_44_845Z-debug-0.log

以前没有更新代码时，使用旧版的代码构建前端工程，是成功的
![image](https://github.com/alldatacenter/alldata/assets/33994422/4381ad28-f396-448b-b44c-900bd6537bd7)

求教大佬们，不知道咋解决
尝试过的方式
1.删除过node_modules 文件夹，并重新 npm install --registry=https://registry.npm.taobao.org 不报错，安装包没问题
但是一到 npm run  dev 就报错
2.按作者大佬的说法，升级npm版本也报错

**Comment by AllDataDC** [comment]
下一个版本回修复此问题，modify micro-ui/package.json, version from 0.4.x to 0.4.3
